- hosts: webserver
  remote_user: ubuntu
  gather_facts: false

  vars:
   - MyMessage: "HELLO WORLD!"

  tasks:
   - name: Nginx setup
     become: yes
     apt: pkg=nginx state=installed update_cache=true

   - name: index.html copy
     become: yes
     template: src=index.html.j2 dest=/var/www/html/index.nginx-debian.html
